version: '3'

services:
  app:
    build:
      context: ./hita-crm
      dockerfile: ./development/app/Dockerfile
    environment:
      - PGHOST=db
      - PGUSER=postgres
    links:
      - db
    volumes:
      - ./hita-crm:/hita-crm
      - storage:/hita-crm/storage
    depends_on:
      - solr
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 3306:5432
  nginx:
    build:
      context: ./hita-crm
      dockerfile: ./development/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 3000:80
  mssql-api:
    entrypoint: ./docker-entrypoint.sh
    command: ["rails", "server", "-p", "5656"]
    build:
      context: ./hita-db-api
      dockerfile: ./development-dockerfile
  solr:
    build:
      context: ./hita-crm
      dockerfile: ./development/solr/Dockerfile
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - hita
    depends_on:
      - db

volumes:
  postgres_data: {}
  solr_data:
  storage:
