module ProposalsHelper
  EQUIPMENTS = [
    'Base de Concreto',
    'Base e costado tanque',
    'Bomba',
    'Chaminé',
    'Correias',
    'Eixo',
    'Flanges',
    'Gaxetas',
    'Hélice',
    'Juntas de expansão',
    'Mangotes e defensas',
    'Moinho',
    'Pisos, bacias e áreas de contenção',
    'Pneus OFF-ROAD',
    'Sapatas em bases de equipamentos (7111)',
    'Silo',
    'Soprador',
    'Suportes e estruturas (fixação a frio)',
    'Tambor correia',
    'Tanque',
    'Telhados e lajes (impermeabilização)',
    'Transformadores',
    'Transportador Helicoidal',
    'Trocador de calor',
    'Tubulação',
    'Turbinas',
    'Válvula',
    'Vaso',
    'Outro'
  ]

  SUBSTRATUM = [
    'Aço carbono',
    'Ferro fundido',
    'Aço inox',
    'Borracha',
    'Concreto',
    'Cerâmica',
    'Polietileno',
    'SuperDuplex',
    'Hastelloy',
    'Alumínio',
    'Cimento-amianto novo',
    'Cimento-amianto velho',
    'Gesso',
    'Madeira',
    'Tijolo',
    'Tijolo de cinzas/Tirolês',
    'Asfalto',
    'Feltro liso',
    'Feltro mineral',
    'Caixilhos de madeira',
    'Caixilhos metálicos',
    'Ardósia',
    'Aço galvanizado',
    'Metais não ferrosos'
  ]

  PROBLEMS = [
    'Abrasão',
    'Erosão',
    'Corrosão química',
    'Corrosão atmosférica',
    'Baixa eficiência energética',
    'Cavitação',
    'Trincas',
    'Desgastes',
    'Vazamento',
    'Corrosão sob isolamento',
    'Corrosão sob tensão',
    'Corrosão por pilha galvânica',
    'Corrosão por materiais dissimilares',
    'Perda de espessura'
  ]

  FLUIDS = [
    '1,1,1-Tricloroetano',
    '2-etoxietanol (Cellosolve)',
    '2-metoxietanol',
    '3-etoxipropionato de etilo',
    'Acetato de amila',
    'Acetato de butilo',
    'Acetato de chumbo',
    'Acetato de cobre',
    'Acetato de etilo',
    'Acetato de metilo',
    'Acetato de pentila',
    'Acetato de sódio',
    'Acetato de éter monometílico de propilenoglicol',
    'Acetato de éter monometílico de propilenoglicol (PMA)',
    'Acetona',
    'Acetona (-)',
    'Acido hidrosulfurico',
    'Adipato de Dioctilo',
    'Adipato de Dioctilo (DOA)',
    'Adipato de dibutil',
    'Alcatrão',
    'Alochols Secundários',
    'Alume (s)',
    'Alume do cromo',
    'Aluminato de sódio',
    'Alvejante',
    'Alúmen de potássio',
    'Amido',
    'Amônia',
    'Anilina',
    'Ar',
    'Ar industrial',
    'Azeite',
    'Azoto',
    'Azoto (-)',
    'Açúcar de beterraba',
    'Benzaldeído',
    'Benzeno',
    'Benzeno (benzol)',
    'Benzeno etílico (-)',
    'Benzenodiol',
    'Bicarbonato de amônio',
    'Bicarbonato de sódio',
    'Bissulfato de magnésio',
    'Bissulfato de sódio',
    'Bissulfito de cálcio',
    'Bissulfito de potássio',
    'Bissulfito de sódio',
    'Borato de sódio',
    'Brometo de potássio',
    'Brometo de sódio',
    'Butano',
    'Butano (-)',
    'Butanol',
    'Carbonato de amônio',
    'Carbonato de bário',
    'Carbonato de cálcio',
    'Carbonato de magnésio',
    'Carbonato de potássio',
    'Carbonato de sódio',
    'Cellosolve de Etilo',
    'Cera de parafina',
    'Cerveja',
    'Chumbo tetraetil',
    'Cianeto de mercúrio',
    'Cianeto de potássio',
    'Cianeto de sódio',
    'Ciclohexano',
    'Ciclohexano (-)',
    'Cidra',
    'Clorato de sódio',
    'Cloreto de Alumínio (seco)',
    'Cloreto de alumínio',
    'Cloreto de amônio',
    'Cloreto de bromo',
    'Cloreto de bário',
    'Cloreto de cobre',
    'Cloreto de cálcio',
    'Cloreto de ferro',
    'Cloreto de magnésio',
    'Cloreto de mercúrio',
    'Cloreto de metileno',
    'Cloreto de metileno (seco)',
    'Cloreto de níquel',
    'Cloreto de potássio',
    'Cloreto de sódio',
    'Cloreto de zinco',
    'Cloreto estanhoso',
    'Cloreto férrico',
    'Cloreto férrico (seco)',
    'Cloro (molhado) (-)',
    'Cloro (molhado)',
    'Cloro (seco)',
    'Cloro (seco) (-)',
    'Clorobenzeno',
    'Clorobenzeno (seco)',
    'Cloroetano (seco)',
    'Clorofórmio',
    'Clorofórmio (seco)',
    'Clorometano (seco)',
    'Combustível de aviação (Avtag) (-)',
    'Combustível de aviação (Avtag)',
    'Cresol',
    'Cromato de sódio',
    'Detergente',
    'Dibutilamina',
    'Dicloreto de etileno',
    'Dicloroetano',
    'Diclorometano (DCM)',
    'Dicromato de potássio',
    'Diesel (-)',
    'Dietanolamina',
    'Dietanolamina (-)',
    'Dietanolamina (DEA)',
    'Dietanolamina (DEA) (-)',
    'Dietanolamina N-Metil (-)',
    'Dietanolamina N-Metil',
    'Dietanolamina N-Metilica (MDEA)',
    'Dietilamina',
    'Dietilenoglicolamina',
    'Dietilenoglicolamina (-)',
    'Dietilenoglicolamina (DGA)',
    'Dietilenotriamina',
    'Difenil isodecilfosfato',
    'Difosfato de potássio',
    'Dimetilamina',
    'Dimetilformamida',
    'Dissulfeto de carbono',
    'Dióxido de carbono',
    'Dióxido de carbono (-)',
    'Dióxido de carbono (seco)',
    'Dióxido de carbono (seco) (-)',
    'Dióxido de enxofre',
    'Dióxido de enxofre (-)',
    'Emulsões de cera',
    'Emulsões de látex de borracha',
    'Esgoto',
    'Espírito branco',
    'Espíritos Minerais / Espíritos Brancos',
    'Espíritos Minerais / Espíritos Brancos (-)',
    'Espíritos brancos',
    'Espíritos minerais',
    'Estireno',
    'Etano',
    'Etano (-)',
    'Etanol',
    'Etanol (78˚C172˚FM)',
    'Etanolamina',
    'Etilenoglicol',
    'Etilenoglicol (-)',
    'Etiletoxipropionato',
    'Fenol',
    'Fenol (-)',
    'Fermento',
    'Ferricianeto de potássio',
    'Ferrocianeto de potássio',
    'Fluido de freio',
    'Fluidos de limpeza a seco',
    'Fluoreto de cálcio',
    'Fluoreto de sódio',
    'Fluorossilicato de sódio',
    'Fluossilicato de Amônio',
    'Formaldeído',
    'Fosfato de Tributilo',
    'Fosfato de amônio',
    'Fosfato de amônio (dibásico)',
    'Fosfato de amônio (tribásico)',
    'Fosfato de difenil isodecil',
    'Fosfato de sódio (dibásico)',
    'Fosfato de sódio (tribásico)',
    'Ftalato de dibutilo',
    'Ftalato de dibutilo (DBP)',
    'Ftalato de dioctilo',
    'Ftalato de dioctilo (DOP)',
    'Gasolina',
    'Gasolina (Ethanol free)',
    'Gasolina (-)',
    'Gasolina (sem etanol) (-)',
    'Gasolina (sem etanol)',
    'Glicerina ou glicerol',
    'Glicerol',
    'Glicerol (-)',
    'Glicose',
    'Graxa',
    'Gás cloro',
    'Gás cloro (-)',
    'Gás hidrogênio',
    'Gás hidrogênio (-)',
    'Gás metilamina',
    'Gás natural',
    'Gás natural (-)',
    'Heptano',
    'Heptano (-)',
    'Hexano',
    'Hexano (-)',
    'Hexanol',
    'Hidrazina',
    'Hidrocarbonetos',
    'Hidrogênio',
    'Hidrogênio (-)',
    'Hidrosulfito de zinco',
    'Hidróxido de bário',
    'Hidróxido de cálcio',
    'Hidróxido de cálcio / água cal',
    'Hidróxido de magnésio',
    'Hidróxido de potássio',
    'Hidróxido de potássio (-)',
    'Hidróxido de sódio',
    'Hidróxido de sódio (-)',
    'Hipoclorito de cálcio',
    'Hipoclorito de sódio',
    'Iodeto de potássio',
    'Isobutanol',
    'Isooctano',
    'Isotiazolinona',
    'Ketchup',
    'Lama de perfuração',
    'Leite',
    'Licor de fermentação',
    'Líquidos de açúcar',
    'Maionese',
    'Margarina',
    'Melaço',
    'Mercúrio',
    'Mesitylene',
    'Mesitylene (-)',
    'Metafosfato de sódio',
    'Metano',
    'Metano (-)',
    'Metano / gás natural (-)',
    'Metano / gás natural',
    'Metanol (In water solution)',
    'Metanol',
    'Metanol (65˚C149˚FM)',
    'Metassilicato de sódio',
    'Metil amil cetona',
    'Metil cellosolve',
    'Metil isobutil cetona (MIBK) (-)',
    'Metil pentil cetona (-)',
    'Metil pentil cetona',
    'Metil-etil-cetona',
    'Metil-etil-cetona (-)',
    'Metilamina (In Water Solution)',
    'Metiletilcetona (MEK)',
    'Misturas de Água / Óleo',
    'Misturas de óleo / água',
    'Monoetanolamina',
    'Monoetanolamina (-)',
    'Monoetanolamina (MEA)',
    'Monofosfato de amônio',
    'Monóxido de carbono',
    'Monóxido de carbono (-)',
    'Mostarda',
    'N-Metiletanolamina',
    'N-metil-2-pirrolidinona (NMP)',
    'N-metilpirrolidona',
    'Nafta',
    'Nafta (-)',
    'Nafta de petróleo',
    'Naftaleno',
    'Naftaleno (-)',
    'Nalco DVE4D002',
    'Nalco DVE4D006',
    'Nalco EC1317A',
    'Nalco EC6303A',
    'Nalco EC6481A',
    'Nalco EC6622A',
    'Nalco EC9356A',
    'Nalco O3VD123',
    'Nalco Ultimer 7751',
    'Nitrato de amônio',
    'Nitrato de cobre',
    'Nitrato de níquel',
    'Nitrato de potássio',
    'Nitrato de prata',
    'Nitrato de sódio',
    'Nitrato férrico',
    'Oleum',
    'Outros (Especificar na observação do pedido)',
    'Ozono (solução aquosa)',
    'Ozono (solução aquosa) (-)',
    'Ozônio (molhado) (-)',
    'Ozônio (molhado)',
    'Ozônio (seco)',
    'Ozônio (seco) (-)',
    'Parafina',
    'Parafina (-)',
    'Pentano',
    'Pentano (-)',
    'Percloroetileno',
    'Percloroetileno (seco)',
    'Permanganato de potássio',
    'Peróxido de hidrogênio',
    'Petrolato',
    'Petróleo, petróleo',
    'Petróleo, petróleo (azedo)',
    'Petróleo, petróleo (refinado)',
    'Piridina',
    'Pirrol',
    'Propanol',
    'Propileno glicol',
    'Propileno glicol (-)',
    'Querosene',
    'Querosene (-)',
    'Querosene (cera de parafina) (-)',
    'Querosene (cera de parafina)',
    'Querosene (parafina) (-)',
    'Querosene (parafina)',
    'Resinas e resinas (naturais)',
    'Resorcinol',
    'Sais de Epsom',
    'Sais de amônio quaternário',
    'Sal de Epsom',
    'Salmoura / água do mar',
    'Salmouras',
    'Sebacato de dibutilo',
    'Sebacato de dibutilo (DBS)',
    'Sebacato de dioctilo',
    'Silicato de sódio',
    'Skydrol',
    'Solução Sulfinol / sulfanol',
    'Solução de amônia',
    'Solução de amônia (-)',
    'Solução de açúcar',
    'Soluções de fertilizantes',
    'Solvente de Stoddard',
    'Soro de leite coalhado',
    'Suco de tomate',
    'Sucos cítricos',
    'Sulfato de Bário',
    'Sulfato de Calcio',
    'Sulfato de alumínio',
    'Sulfato de alumínio de potássio',
    'Sulfato de alumínio e potássio',
    'Sulfato de amónio níquel',
    'Sulfato de amônia',
    'Sulfato de cobre',
    'Sulfato de hidrogênio',
    'Sulfato de hidrogênio (-)',
    'Sulfato de magnésio',
    'Sulfato de níquel',
    'Sulfato de potássio',
    'Sulfato de potássio de cromo',
    'Sulfato de sódio',
    'Sulfato de zinco',
    'Sulfato ferroso',
    'Sulfato férrico',
    'Sulfeto de bário',
    'Sulfeto de potássio',
    'Sulfeto de sódio',
    'Sulfito de potássio',
    'Sulfóxido de dimetilo',
    'Terebintina',
    'Tetracloreto de carbono',
    'Tetracloreto de carbono (seco)',
    'Tetracloroetileno / Percloroetileno',
    'Tetraetilenoglicol',
    'Tetraetilenoglicol (-)',
    'Tetraidrofurano',
    'Tinta de emulsão',
    'Tinta à base de água',
    'Tolueno',
    'Tolueno (-)',
    'Tolueno (toluol)',
    'Tolueno (toluol) (-)',
    'Transferência de óleo',
    'Tricloreto de antimônio',
    'Tricloroetileno',
    'Triclorotrifluoroetano',
    'Trietanolamina',
    'Trietanolamina (-)',
    'Trietanolamina (TEA)',
    'Trietanolamina (TEA) (-)',
    'Trietileno glicol',
    'Trietileno glicol (-)',
    'Trietilenotetramina',
    'Trióxido de enxofre',
    'Trióxido de enxofre (-)',
    'Uréia',
    'Uísque e vinho',
    'Vinagre',
    'Xileno',
    'Xileno (-)',
    'Xileno (xilol) (-)',
    'Xileno (xilol)',
    'Água',
    'Azeite de dendê',
    'Manteiga',
    'n-butanol (-)',
    'n-butanol',
    'n-hexanol',
    'n-hexanol (-)',
    'Suco de maçã',
    'Ácido Cresílico',
    'Ácido Fluorossilicico',
    'Ácido Metacrílico (MAA)',
    'Ácido acrílico',
    'Ácido acético',
    'Ácido acético (-)',
    'Ácido acético (glacial)',
    'Ácido acético (glacial) (-)',
    'Ácido bromídrico',
    'Ácido carbónico',
    'Ácido cloroacético',
    'Ácido clorossulfônico',
    'Ácido clorídrico',
    'Ácido clorídrico (-)',
    'Ácido crômico',
    'Ácido cítrico',
    'Ácido esteárico',
    'Ácido esteárico (sólido)',
    'Ácido fosfórico',
    'Ácido fosfórico (-)',
    'Ácido fólico',
    'Ácido fórmico',
    'Ácido hidrocholoric',
    'Ácido lático',
    'Ácido maleico',
    'Ácido nitroso',
    'Ácido nítrico',
    'Ácido perclórico',
    'Ácido salicílico',
    'Ácido sulfúrico',
    'Ácido sulfúrico (-)',
    'Ácido tartárico',
    'Ácido tânico',
    'Água de Lima',
    'Água de bromo (saturada)',
    'Água desionizada',
    'Água destilada',
    'Água destilada (aerada)',
    'Água do mar',
    'Água fresca',
    'Água mineral',
    'Águas de processo de mina (ácidas)',
    'Álcoois Secundários',
    'Álcoois Secundários (-)',
    'Álcoois superiores',
    'Álcoois superiores (-)',
    'Álcoois terciários',
    'Álcoois terciários (-)',
    'Álcool Amílico (-)',
    'Álcool Amílico',
    'Álcool Butílico / Butanol',
    'Álcool Butílico / n-Butanol',
    'Álcool Metílico / Metanol',
    'Álcool Metílico / Metanol (65˚C149˚FM)',
    'Álcool Propílico / Propanol',
    'Álcool etílico / etanol (78˚C172˚FM)',
    'Álcool etílico / etanol',
    'Álcool isobutílico (AIB)',
    'Álcool isobutílico (IBN)',
    'Álcool isopropílico',
    'Álcool isopropílico (-)',
    'Álcool isopropílico (IPA)',
    'Álcool isopropílico (IPA) (-)',
    'Éter butílico',
    'Éter dietílico',
    'Éter isopropílico',
    'Óleo alto',
    'Óleo azedo / mistura de salmoura',
    'Óleo combustível',
    'Óleo cru',
    'Óleo cru, azedo',
    'Óleo cru, doce',
    'Óleo de banha',
    'Óleo de bunker',
    'Óleo de corte (emulsões de água)',
    'Óleo de creosoto',
    'Óleo de côco',
    'Óleo de linhaça',
    'Óleo de milho',
    'Óleo de petróleo',
    'Óleo de salada',
    'Óleo de semente de algodão',
    'Óleo de silicone',
    'Óleo de soja',
    'Óleo de transformador',
    'Óleo de tungue',
    'Óleo diesel',
    'Óleo hidráulico',
    'Óleo hidráulico à base de petróleo',
    'Óleo lubrificante',
    'Óleos de corte (emulsões de água)',
    'Óleos de corte, emulsões de água',
    'Óleos para bunker (óleos combustíveis)',
    'Óxido nitroso (-)',
    'Óxido nitroso',
    'óleo de castor',
    'óleo de fígado de bacalhau',
    'óleo de pinho'
  ].sort
end
