FROM solr:7.0.1

COPY ./config/solr/solrconfig.xml /opt/solr/server/solr/configsets/_default/conf/solrconfig.xml
COPY ./config/solr/schema.xml /opt/solr/server/solr/configsets/_default/conf/schema.xml
